brew "ack"
brew "coreutils"
brew "curl"
brew "findutils"
brew "gawk"
brew "git"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnutls"
brew "go"
brew "gpg"
brew "grep"
brew "grpc"
brew "hashicorp/tap/consul"
brew "hashicorp/tap/nomad"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"
brew "hexedit"
brew "jq"
brew "llvm"
brew "nmap"
brew "node"
brew "protobuf"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "withgraphite/tap/graphite"
brew "ykman"
brew "zsh"
brew "zsh-completions"
cask "google-cloud-sdk"

# brew "arduino-cli"
# brew "certbot"
# brew "grafana/grafana/cortextool"
# brew "leveldb"
# brew "logcli"
# brew "minicom"
# brew "stripe/stripe-cli/stripe"
# brew "node@16"
