let g:pathogen_disabled = []
call pathogen#infect()

runtime config/core.vim

function LoadConfig(name)
    if (index(g:pathogen_disabled, a:name) < 0)
        execute "runtime config/" . a:name . ".vim"
    endif
endfunction

call LoadConfig("vim-colors-solarized")
call LoadConfig("vim-airline")
call LoadConfig("nerdtree")
call LoadConfig("vim-go")
call LoadConfig("vim-better-whitespace")
call LoadConfig("vim-pandoc-syntax")
call LoadConfig("vim-pandoc")
